# Generated by Django 5.1.5 on 2025-02-03 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadano_app', '0009_remove_ciudadano_groups_and_more'),
        ('shared', '0003_alter_reporte_ciudadano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('Seguro', 'Seguro'), ('Riesgo', 'Riesgo'), ('Peligroso', 'Peligroso')], default='Seguro', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='reporte',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudadano_app.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ciudadano_app.ciudadano')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
