# Generated by Django 5.1 on 2025-02-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_sector_alter_reporte_ciudadano_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
