# Generated by Django 5.1 on 2025-02-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0013_alter_entidadmunicipal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalinformativo',
            name='entidad_municipal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canales', to='entidad_municipal_app.entidadmunicipal'),
        ),
    ]
