# Generated by Django 5.1 on 2025-02-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0014_canalinformativo_entidad_municipal'),
        ('entidad_municipal_app', '0015_entidadmunicipal_groups_and_more'),
    ]

    operations = [
    ]
