# Generated by Django 5.1 on 2025-02-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_municipal_app', '0016_merge_20250201_1345'),
        ('entidad_municipal_app', '0019_espaciopublico_descripcion_and_more'),
    ]

    operations = [
    ]
